---
# TODO YELL AT -FUCKING EVERYONE- FOR NOT ALLOWING NO UID PGP KEYS
# IT HAS BROKEN FUCKING EVERYTHING
# THANK U FOR COMING TO MY TED TALK
- apt_key:
    data: "{{ lookup('file', 'apt/tor.asc') }}"
    id: A3C4F0F979CAA22CDBA8F512EE8CBC9E886DDD89
    keyring: /etc/apt/trusted.gpg.d/deb.torproject.org-keyring.gpg

- apt_repository:
    repo: deb https://deb.torproject.org/torproject.org {{ ansible_distribution_release }} main
    state: present
    filename: tor

- name: Install tor packages
  apt:
    name:
      - deb.torproject.org-keyring
      - python-torctl
      - tor
      - torsocks
      - tor-arm

- name: setup torsocks to accept inbound connections
  lineinfile:
    path: /etc/tor/torsocks.conf
    line: "AllowInbound 1"

- name: enable tor service
  systemd:
    name: tor
    enabled: yes
    masked: no
    state: started
  when: not dockerenv.stat.exists
