sudo: required
services:
  - docker

cache:
  pip: {}

addons:
  apt:
    packages:
      - wget
      - unzip
      - python-pip
      - qemu-system-x86

env:
  global:
    - REPO=hashbang/shell-server

before_install:
  - test -f /usr/local/bin/packer || (wget -O packer.zip https://releases.hashicorp.com/packer/1.2.4/packer_1.2.4_linux_amd64.zip && unzip -o packer.zip && sudo mv packer /usr/local/bin/)
  - sudo -H pip install 'ansible>=2.5'
  
script:
  - sudo make docker

# after_success:
#   - if [ "$TRAVIS_BRANCH" == "master" ]; then docker login -u $DOCKER_USER -p $DOCKER_PASS && docker tag shell-server $REPO:latest && docker push $REPO; fi
