- name: Install Administrator PGP keys
  block:
    - name: create temporary build directory
      tempfile:
        state: directory
      register: gnupghome
    - name: Import administrator PGP keys from keyserver
      shell: |
        GNUPGHOME="{{ gnupghome.path }}"; \
        for server in $(shuf -e ha.pool.sks-keyservers.net \
                                hkp://p80.pool.sks-keyservers.net:80 \
                                keyserver.ubuntu.com \
                                hkp://keyserver.ubuntu.com:80 \
                                pgp.mit.edu ) ; \
        do \
          gpg --keyserver "$server" --recv-keys "{{ item }}" && break || : ; \
        done
      args:
        executable: /bin/bash
      with_items:
        - "954A3772D62EF90E4B31FBC6C91A9911192C187A" # daurnimator
        - "0A1F87C7936EB2461C6A9D9BAD9970F98EB884FD" # DeviaVir
        - "C92FE5A3FBD58DD3EC5AA26BB10116B8193F2DBD" # groved
        - "F2B7999666D83093F8D4212926CDD32189AA2885" # dpflug
        - "AE2D535ABD2E5B42CE1E97110527B4EFFB4A3AEB" # KellerFuchs
        - "6B61ECD76088748C70590D55E90A401336C8AAA9" # lrvick
        - "A251FDF79171F98674EB2176FCC2D6E33BA86209" # ryan
    - name: create hashbang lib directory
      file: path=/var/lib/hashbang state=directory
    - name: Export administrator pgp keys to combined keychain file
      shell: |
        GNUPGHOME={{ gnupghome.path }} \
        gpg \
          -q \
          --batch \
          --yes \
          --export \
          --export-options export-clean,export-minimal \
          -o /var/lib/hashbang/admins.gpg
      args:
        executable: /bin/bash

- name: Install Welcome Templates and Man page
  block:
  - file:
      state: directory
    with_filetree: templates/
    when: item.state == 'directory'
  - template:
      src: "{{ item.src }}"
      dest: "{{ item.path | basename | regex_replace('.j2','') }}"
      mode: "{{ item.mode }}"
    with_filetree: templates/
    when: item.state == 'file'
