---
- name: Install DNS packages
  apt:
    name: "{{ item }}"
  with_items:
  - unbound
  - unbound-anchor
  - dns-root-data
  - dnsutils
  - ldnsutils
  - resolvconf

- name: setup localhost as default nameserver
  lineinfile:
    path: /etc/resolvconf/resolv.conf.d/base
    create: true
    line: "nameserver 127.0.0.1"

- name: setup hashbang.sh as default domain
  lineinfile:
    path: /etc/resolvconf/resolv.conf.d/tail
    create: true
    line: "domain hashbang.sh"

- name: Setup unbound configuration
  block:
  - name: Use DNS root hints from the dns-root-data Debian package
    blockinfile:
      path: /etc/unbound/unbound.conf.d/debian.conf
      marker: "# {mark} ANSIBLE - DNS Root Hints"
      create: true
      block: |
        server:
          root-hints: "/usr/share/dns/root.hints"
  - name: Prefetch popular domains before the cache expires
    blockinfile:
      path: /etc/unbound/unbound.conf.d/prefetch.conf
      marker: "# {mark} ANSIBLE - Prefetch popular domains"
      create: true
      block: |
        server:
          prefetch:     yes
          prefetch-key: yes
  - name: Enable RFC 7816 "DNS Query Name Minimisation to Improve Privacy"
    blockinfile:
      path: /etc/unbound/unbound.conf.d/qname-minimisation.conf
      marker: "# {mark} ANSIBLE - Enable RFC 7816"
      create: true
      block: |
        server:
            qname-minimisation: yes

- name: Enable & reload services
  when: not dockerenv.stat.exists
  systemd:
    name: "{{ item }}"
    enabled: yes
    masked: no
    state: reloaded  # TODO: This should be a handler instead

  with_items:
    - unbound
    - unbound-resolvconf
    - resolvconf
