---
- name: Install DNS packages
  apt:
    update_cache: yes
    name:
      - unbound
      - unbound-anchor
      - dns-root-data
      - dnsutils
      - ldnsutils
      - resolvconf

- name: setup localhost as default nameserver
  lineinfile:
    path: /etc/resolvconf/resolv.conf.d/base
    create: true
    line: "nameserver 127.0.0.1"

- name: setup hashbang.sh as default domain
  lineinfile:
    path: /etc/resolvconf/resolv.conf.d/tail
    create: true
    line: "domain hashbang.sh"

- name: Setup unbound configuration
  block:
  - name: Use DNS root hints from the dns-root-data Debian package
    blockinfile:
      path: /etc/unbound/unbound.conf.d/debian.conf
      marker: "# {mark} ANSIBLE - DNS Root Hints"
      create: true
      block: |
        server:
          root-hints: "/usr/share/dns/root.hints"
  - name: Prefetch popular domains before the cache expires
    blockinfile:
      path: /etc/unbound/unbound.conf.d/prefetch.conf
      marker: "# {mark} ANSIBLE - Prefetch popular domains"
      create: true
      block: |
        server:
          prefetch:     yes
          prefetch-key: yes
  - name: Enable RFC 7816 "DNS Query Name Minimisation to Improve Privacy"
    blockinfile:
      path: /etc/unbound/unbound.conf.d/qname-minimisation.conf
      marker: "# {mark} ANSIBLE - Enable RFC 7816"
      create: true
      block: |
        server:
            qname-minimisation: yes

  - name: unbound configuration hardening
    copy:
      dest: /etc/unbound/unbound.conf.d/harden.conf
      content: |
        server:
          # Do not expose information about the running deamon
          hide-identity: yes
          hide-version:  yes

          # Harden against ridiculously-short buffer sizes (potential DoS vector)
          # This is against spec, but we aren't a public resolver.
          harden-short-bufsize: yes

          # Harden against abnormaly large queries (same reasoning)
          harden-large-queries: yes

          # Return NXDOMAIN for queries under a terminal known (and DNSSEC-validated)
          #   to be NXDOMAIN.  Improves caching and avoids certain attacks
          harden-below-nxdomain: yes

          # Use 0x20-encoded random nonces for authenticating queries.
          # Implementation of draft-dns-0x20, makes DNS poisoning harder
          use-caps-for-id: yes

          # Minimises queries sent upstream
          # Avoids information disclosure to root/TLD DNS servers & improves caching
          qname-minimisation: yes

- name: Enable & reload services
  when: not dockerenv.stat.exists
  systemd:
    name: "{{ item }}"
    enabled: yes
    masked: no
    state: reloaded  # TODO: This should be a handler instead

  with_items:
    - unbound

# TODO This is a hotfix, try and merge with above if possible
- name: Enable & restat services
  when: not dockerenv.stat.exists
  systemd:
    name: "{{ item }}"
    enabled: yes
    masked: no
    state: restarted  # TODO: This should be a handler instead

  with_items:
    - unbound-resolvconf
    - resolvconf
