---
- hosts: all
  gather_facts: false
  pre_tasks:
  - name: Install python2 for Ansible
    raw: bash -c "test -e /usr/bin/python || (apt -qqy update && apt install -qqy python-minimal)"
    register: output
    changed_when: output.stdout != ""
  - name: Gathering Facts
    setup:

  tasks:

  - apt_key:
      keyserver: keyserver.ubuntu.com
      id: 93C4A3FD7BB9C367

  - apt_repository:
      repo: deb http://ppa.launchpad.net/ansible/ansible/ubuntu trusty main
      state: present

  - name: Install minimum system packages
    apt:
      name: "{{ item }}"
    with_items:
    - ansible
    - git
    - gnupg
    - apt-transport-https
    - unattended-upgrades
    - systemd
    - apt-utils
    - lsb-release
    - curl
    - initscripts
    - systemd
    - udev
    - util-linux
    - openssh-server

  - name: Determine if we are in a docker environment
    stat: path=/.dockerenv
    register: dockerenv

  - name: Run Docker preinit task
    include_tasks: tasks/docker/main.pre.yml
    when: dockerenv.stat.exists
    ignore_errors: True

  - name: Include tasks files
    include_tasks: "tasks/{{ item }}/main.yml"
    with_items:
    - tor
    - hashbang
    - logging
    - dns
    - mail
    - packages
    - profile
    - misc
    - ldap-nss
    - security

  - name: Run Docker postinit task
    include_tasks: tasks/docker/main.post.yml
    when: dockerenv.stat.exists
    ignore_errors: True
