---
- hosts: all
  gather_facts: false
  pre_tasks:
  - name: Install python2 for Ansible
    raw: bash -c "test -e /usr/bin/python || (apt -qqy update && apt install -qqy python-minimal)"
    register: output
    changed_when: output.stdout != ""
  - name: Gathering Facts
    setup:

  tasks:
  - name: Determine if we are in a docker environment
    stat: path=/.dockerenv
    register: dockerenv
  - include_tasks: tasks/docker.yml
    when: dockerenv.stat.exists
    ignore_errors: True
  - include_tasks: tasks/packages.yml
#- import_playbook: includes/setup/misc.yml

# none of the templates for these exist yet
#- import_playbook: includes/setup/install-config.yml

# somehow conditionally include this only if target is docker
#- import_playbook: includes/docker/resolvconf.yml

# Everything under this point doesn't exist?
#- import_playbook: includes/setup/apt/configure-selections.yml
#- import_playbook: includes/config/tools/msmtp.yml

# optional depending on whether or not we version-control the unit files
# which we probably won't
#- import_playbook: includes/docker/disable-systemd-units.yml

#- import_playbook: includes/machine/setup-journal.yml
#- import_playbook: includes/machine/update-grub.yml
#- import_playbook: includes/machine/fstrim.yml
