---
- hosts: all
  gather_facts: false
  pre_tasks:
  - name: Install python2 for Ansible
    raw: bash -c "test -e /usr/bin/python || (apt -qqy update && apt install -qqy python-minimal)"
    register: output
    changed_when: output.stdout != ""
  - name: Gathering Facts
    setup:

  tasks:
  - name: Determine if we are in a docker environment
    stat: path=/.dockerenv
    register: dockerenv
  - include_tasks: tasks/docker.yml
    when: dockerenv.stat.exists
    ignore_errors: True
  - include_tasks: tasks/packages.yml
  - include_tasks: tasks/tor.yml
  - include_tasks: tasks/cron.yml
  - include_tasks: tasks/dns.yml
  - include_tasks: tasks/docker.yml
  - include_tasks: tasks/hashbang.tf
  - include_tasks: tasks/ldap-nss.yml
  - include_tasks: tasks/logging.yml
  - include_tasks: tasks/mail.yml
  - include_tasks: tasks/misc.yml
  - include_tasks: tasks/profile.yml
  - include_tasks: tasks/security.yml
