---
- hosts: all
  gather_facts: false
  pre_tasks:
  - name: Install python2 for Ansible
    raw: bash -c "test -e /usr/bin/python || (apt -qqy update && apt install -qqy python-minimal)"
    register: output
    changed_when: output.stdout != ""
  - name: Gathering Facts
    setup:

  tasks:

  - name: Install minimum system packages
    apt:
      update_cache: true
      name: "{{ item }}"
    with_items:
    - ansible
    - git
    - gnupg
    - apt-transport-https
    - unattended-upgrades
    - systemd
    - apt-utils
    - lsb-release
    - curl
    - initscripts
    - systemd
    - udev
    - util-linux
    - openssh-server

  - name: Remove undesirable apt files
    file:
      path: /etc/apt/{{ item }}
      state: absent
    with_items:
      - trusted.gpg # Use trusted.gpg.d rather than a monolithic file!
      - # We aren't running Ubuntu ...
        sources.list.d/ppa_launchpad_net_ansible_ansible_ubuntu.list


  - name: Install latest ansible
    apt:
      name: ansible
      state: latest
      update_cache: yes

  - name: Determine if we are in a docker environment
    stat: path=/.dockerenv
    register: dockerenv

  - name: Run Docker preinit task
    include_tasks: tasks/docker/main.pre.yml
    when: dockerenv.stat.exists
    ignore_errors: True

  - name: Include tasks files
    include_tasks: "tasks/{{ item }}/main.yml"
    with_items:
    - tor
    - hashbang
    - logging
    - dns
    - mail
    - packages
    - profile
    - misc
    - ldap-nss
    - security

  - name: Run Docker postinit task
    include_tasks: tasks/docker/main.post.yml
    when: dockerenv.stat.exists
    ignore_errors: True
