---
- name: Configure ssh to use sss for authorized-keys
  blockinfile:
    path: /etc/ssh/sshd_config
    marker: "# {mark} ANSIBLE - sss config for ssh"
    block: |
      AuthorizedKeysFile        none
      AuthorizedKeysCommand     /usr/bin/sss_ssh_authorizedkeys
      AuthorizedKeysCommandUser nobody

- name: Configure sssd to use custom ldap server
  blockinfile:
    path: /etc/sssd/sssd.conf
    marker: "# {mark} ANSIBLE - LDAP configuration for sss"
    mode: 0600
    create: true
    block: |
      [sssd]
      domains = HASHBANG
      services = nss, pam, ssh
      config_file_version = 2

      [nss]


      [domain/HASHBANG]
      enumerate = TRUE
      id_provider = ldap
      access_provider = ldap
      ldap_uri = ldaps://ldap.hashbang.sh
      ldap_search_base = dc=hashbang,dc=sh
      ldap_tls_reqcert = demand
      ldap_user_search_base = ou=People,dc=hashbang,dc=sh
      ldap_user_ssh_public_key = sshPublicKey
      ldap_pwd_policy = none
      ldap_access_order = host
      ldap_user_authorized_host = host
      cache_credentials = true

      [pam]
      id_provider = proxy

- name: Update Nsswitch to not use sss for sudoers
  lineinfile:
    create: true
    path: /etc/nsswitch.conf
    regexp: "^sudoers:"
    line: "sudoers:        files"

- name: Update pam to use sss
  block:
  - name: update pam common-account to use sss
    block:
    - pamd:
        name: common-account
        type: account
        control: required
        module_path: pam_nologin.so
    - pamd:
        name: common-account
        type: account
        control: sufficient
        module_path: pam_sss.so
    - pamd:
        name: common-account
        type: account
        control: sufficient
        module_path: pam_unix.so
    - pamd:
        name: common-account
        type: account
        control: sufficient
        module_path: pam_localuser.so
    - pamd:
        name: common-account
        type: account
        control: required
        module_path: pam_deny.so

  - name: update pam common-auth to use sss
    block:
    - pamd:
        name: common-auth
        type: auth
        control: sufficient
        module_path: pam_sss.so
    - pamd:
        name: common-auth
        type: auth
        control: sufficient
        module_path: pam_unix.so
        modul_arguments: 'use_first_pass'
    - pamd:
        name: common-auth
        type: auth
        control: required
        module_path: pam_deny.so

  - name: Update pam common-password to use sss
    block:
    - pamd:
        name: common-password
        type: password
        control: requisite
        module_path: pam_pwquality.so
        module_arguments: 'retry=3'
    - pamd:
        name: common-password
        type: password
        control: sufficient
        module_path: pam_sss.so
        modul_arguments: 'use_authtok'
    - pamd:
        name: common-password
        type: password
        control: sufficient
        module_path: pam_unix.so
        module_arguments: 'obscure use_authtok try_first_pass sha512'
    - pamd:
        name: common-password
        type: password
        control: requisite
        module_path: pam_deny.so

  - name: Update pam common-session to use sss
    block:
    - pamd:
        name: common-session
        type: session
        control: substack
        module_arguments: 'common-session-noninteractive'
    - pamd:
        name: common-session
        type: session
        control: optional
        module_path: pam_mkhomedir.so
    - pamd:
        name: common-session
        type: session
        control: optional
        module_path: pam_umask.so
        module_arguments: 'usergroups'

  - name: Update pam common-session-noninteractive to use sss
    block:
    - pamd:
        name: common-session-noninteractive
        type: session
        control: required
        module_path: pam_env.so
    - pamd:
        name: common-session-noninteractive
        type: session
        control: required
        module_path: pam_namespace.so
        module_arguments: 'unmnt_remnt'
    - pamd:
        name: common-session-noninteractive
        type: session
        control: required
        module_path: pam_limits.so
    - pamd:
        name: common-session-noninteractive
        type: session
        control: required
        module_path: pam_systemd.so
    - pamd:
        name: common-session-noninteractive
        type: session
        control: required
        module_path: pam_exec.so
        module_arguments: 'type=open_session /etc/security/limits.sh'
    - pamd:
        name: common-session-noninteractive
        type: session
        control: sufficient
        module_path: pam_sss.so
    - pamd:
        name: common-session-noninteractive
        type: session
        control: sufficient
        module_path: pam_unix.so
    - pamd:
        name: common-session-noninteractive
        type: session
        control: required
        module_path: pam_deny.so

  - name: Update adt/sudo/cron to use common-session-interactive as substack
    pamd:
      name: '{{ item }}'
      type: session
      control: substack
      module_arguments: 'common-session-noninteractive'
    with_items:
      - adt
      - sudo
      - cron

- name: Setup NSLCD to ldap hashbang settings
  copy:
    dest: /etc/nslcd.conf
    content: |
      uid nslcd
      gid nslcd

      uri ldaps://ldap.hashbang.sh/

      base dc=hashbang,dc=sh

      tls_reqcert never
      tls_cacertfile /etc/ssl/certs/ca-certificates.crt
